# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_thr <- function(a, lam, pos) {
    .Call('_Sparse-and-Functional-PCA_soft_thr', PACKAGE = 'Sparse-and-Functional-PCA', a, lam, pos)
}

sfpca_fixed <- function(x, lamu, lamv, alphau, alphav, Omegu, Omegv, startu, startv, posu, posv, maxit) {
    .Call('_Sparse-and-Functional-PCA_sfpca_fixed', PACKAGE = 'Sparse-and-Functional-PCA', x, lamu, lamv, alphau, alphav, Omegu, Omegv, startu, startv, posu, posv, maxit)
}

